### ISSUE TITLE
水平垂直居中

### ISSUE THREAD

**Issue by sihai00** [sihai00/interview#19]
# 让一个 div 水平垂直居中
```html
<div class="parent">
  <div class="child"></div>
</div>
```

## 绝对定位
第一种
```css
div.parent {
    position: relative; 
}
div.child {
    position: absolute; 
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);  
}
```
第二种
```css
div.parent {
    position: relative; 
}
div.child {
    width: 50px;
    height: 10px;
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    margin: auto;
}
```
第三种：子元素定宽高
```css
div.parent {
    position: relative; 
}
div.child {
    width: 50px;
    height: 10px;
    position: absolute;
    top: 50%;
    left: 50%;
    margin-left: -25px;
    margin-top: -5px;
}
```

## 弹性布局
第一种
```css
div.parent {
    display: flex;
    justify-content: center;
    align-items: center;
}
```
第二种
```css
div.parent{
  display:flex;
}
div.child{
  margin:auto;
}
```

## 网格布局
```css
div.parent {
    display: grid;
}
div.child {
    justify-self: center;
    align-self: center;
}
```

## 基线对齐
第一种：
```css
div.parent {
    font-size: 0;
    text-align: center;
    height: 500px;
    line-height: 500px;
}
div.child{
    width: 100px;
    height: 100px;
    display: inline-block;
}
```
第二种：
```css
div.parent {
    font-size: 0;
    text-align: center;
    &::before {
        content: "";
        display: inline-block;
        width: 0;
        height: 100%;
        vertical-align: middle;
    }
}
div.child{
  display: inline-block;
  vertical-align: middle;
}
```

## 表格对齐
```css
div.parent {
  display: table-cell;
  text-align: center;
  vertical-align: middle;
}
div.child {
  display: table-cell
}
```
